INSERT INTO stations (name, line_id)
VALUES
    ('Pantitlán', 1),
    ('Zaragoza', 1),
    ('Gómez Farías', 1),
    ('Boulevard Puerto Aéreo', 1),
    ('Balbuena', 1),
    ('Moctezuma', 1),
    ('San Lázaro', 1),
    ('Candelaria', 1),
    ('Merced', 1),
    ('Pino Suárez', 1),
    ('Isabel la Católica', 1),
    ('Salto del Agua', 1),
    ('Balderas', 1),
    ('Cuauhtémoc', 1),
    ('Insurgentes', 1),
    ('Sevilla', 1),
    ('Chapultepec', 1),
    ('Juanacatlán', 1),
    ('Tacubaya', 1),
    ('Observatorio', 1)
    ('Cuatro Caminos', 2),
    ('Panteones', 2),
    ('Tacuba', 2),
    ('Cuitlahuac', 2),
    ('Popotla', 2),
    ('Colegio Militar', 2),
    ('Normal', 2),
    ('San Cosme', 2),
    ('Revolución', 2),
    ('Hidalgo', 2),
    ('Bellas Artes', 2),
    ('Allende', 2),
    ('Zócalo', 2),
    ('Pino Suárez', 2),
    ('San Antonio Abad', 2),
    ('Chabacano', 2),
    ('Viaducto', 2),
    ('Xola', 2),
    ('Villa de Cortés', 2),
    ('Nativitas', 2),
    ('Portales', 2),
    ('Ermita', 2),
    ('General Anaya', 2),
    ('Tasqueña', 2)
    ('Indios Verdes', 3),
    ('Deportivo 18 de Marzo', 3),
    ('Potrero', 3),
    ('La Raza', 3),
    ('Tlatelolco', 3),
    ('Guerrero', 3),
    ('Hidalgo', 3),
    ('Juárez', 3),
    ('Balderas', 3),
    ('Niños Héroes', 3),
    ('Hospital General', 3),
    ('Centro Médico', 3),
    ('Etiopía/Plaza de la Transparencia', 3),
    ('Eugenia', 3),
    ('División del Norte', 3),
    ('Zapata', 3),
    ('Coyoacán', 3),
    ('Viveros/Derechos Humanos', 3),
    ('Miguel Ángel de Quevedo', 3),
    ('Copilco', 3),
    ('Universidad', 3),
    ('Martín Carrera', 4),
    ('Talismán', 4),
    ('Bondojito', 4),
    ('Consulado', 4),
    ('Canal del Norte', 4),
    ('Morelos', 4),
    ('Candelaria', 4),
    ('Fray Servando', 4),
    ('Jamaica', 4),
    ('Santa Anita', 4),
    ('Pantitlán', 5),
    ('Hangares', 5),
    ('Terminal Aérea', 5),
    ('Oceanía', 5),
    ('Aragón', 5),
    ('Eduardo Molina', 5),
    ('Consulado', 5),
    ('Valle Gómez', 5),
    ('Misterios', 5),
    ('La Raza', 5),
    ('Autobuses del Norte', 5),
    ('Instituto del Petróleo', 5),
    ('Politécnico', 5),